### ISSUE TITLE
Issue when user are deleted from ldap

### ISSUE THREAD

**Issue by alexist** [Jahia/LDAP-provider#2]
In ldap-provider version 2.0.3, method lookupUser query ldap to retrieve user. When user is deleted from ldap, the method return null

If this user was for example, a "server administrator", the "Server Roles" in admin GUI will display a stascktrace due to NullPointerException.

The issue come from lookupUser :  RolesHandler.getRoles() is calling userRoutingService.lookupUser that delegate to JCR and LDAP provider. 
Has user is stored in JCR with external à true, JCRProvider return null
Has user is no more in LDAP, LDAP PRovider  return null

The result roles return by RolesHandler.getRoles() will contain a null value 

LDAP Provider should perform a JCR query when LDAP return null

**Comment by alexist** [comment]
the stacktrace :
2015-01-29 14:01:18,223: ERROR [TemplateScriptFilter] - Error while rendering content
org.jahia.services.render.RenderException: org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'view' of flow 'jnt_manageRoles/html/manageRoles.flow'
        at org.jahia.services.render.webflow.WebflowDispatcherScript.execute(WebflowDispatcherScript.java:231)
        at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:150)
        at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
        at org.jahia.services.render.RenderService.render(RenderService.java:234)
        at org.jahia.taglibs.template.include.ModuleTag.render(ModuleTag.java:659)
        at org.jahia.taglibs.template.include.ModuleTag.doEndTag(ModuleTag.java:354)
        at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_template_module_0(org.apache.jsp.jmix_005flist.html.list_jsp:434)
        at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_forEach_0(org.apache.jsp.jmix_005flist.html.list_jsp:399)
        at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_otherwise_0(org.apache.jsp.jmix_005flist.html.list_jsp:359)
        at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_choose_0(org.apache.jsp.jmix_005flist.html.list_jsp:176)
        at org.apache.jsp.jmix_005flist.html.list_jsp._jspService(org.apache.jsp.jmix_005flist.html.list_jsp:93)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:384)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:171)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:168)
        at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:167)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handleInclude(ServletHandler.java:221)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:176)
        at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:97)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
        at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.felix.http.proxy.ProxyServlet.service(ProxyServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.jahia.services.render.scripting.RequestDispatcherScript.execute(RequestDispatcherScript.java:154)
        at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:150)
        at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
        at org.jahia.services.render.RenderService.render(RenderService.java:234)
        at org.jahia.taglibs.template.include.ModuleTag.render(ModuleTag.java:659)
        at org.jahia.taglibs.template.include.AreaTag.render(AreaTag.java:426)
        at org.jahia.taglibs.template.include.ModuleTag.doEndTag(ModuleTag.java:354)
        at org.jahia.taglibs.template.include.AreaTag.doEndTag(AreaTag.java:408)
        at org.apache.jsp.jnt_005ftemplate.html.template_serverSettings_jsp._jspx_meth_template_area_0(org.apache.jsp.jnt_005ftemplate.html.template_serverSettings_jsp:308)
        at org.apache.jsp.jnt_005ftemplate.html.template_serverSettings_jsp._jspService(org.apache.jsp.jnt_005ftemplate.html.template_serverSettings_jsp:113)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:384)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:171)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:168)
        at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:167)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handleInclude(ServletHandler.java:221)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:176)
        at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:97)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
        at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.felix.http.proxy.ProxyServlet.service(ProxyServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.jahia.services.render.scripting.RequestDispatcherScript.execute(RequestDispatcherScript.java:154)
        at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:150)
        at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
        at org.jahia.services.render.RenderService.render(RenderService.java:234)
        at org.jahia.services.render.filter.TemplateNodeFilter.prepare(TemplateNodeFilter.java:142)
        at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
        at org.jahia.services.render.RenderService.render(RenderService.java:234)
        at org.jahia.bin.Render.doGet(Render.java:281)
        at org.jahia.bin.Render.handleRequest(Render.java:848)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.jahia.services.seo.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:153)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jahia.bin.filters.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:145)
        at org.jahia.bin.filters.CompositeFilter.doFilter(CompositeFilter.java:127)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jahia.bin.filters.jcr.JcrSessionFilter.doFilter(JcrSessionFilter.java:149)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jahia.bin.filters.spnego.SpnegoHttpFilter.doFilter(SpnegoHttpFilter.java:122)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jahia.security.license.LicenseFilter.doFilter(LicenseFilter.java:88)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jahia.bin.filters.MaintenanceFilter.doFilter(MaintenanceFilter.java:123)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'view' of flow 'jnt_manageRoles/html/manageRoles.flow'
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.wrap(FlowExecutionImpl.java:571)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:262)
        at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:169)
        at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:183)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.jahia.services.render.webflow.WebflowDispatcherScript.execute(WebflowDispatcherScript.java:225)
        ... 158 more
Caused by: java.lang.IllegalStateException: Exception occurred rendering view org.springframework.web.servlet.view.InternalResourceView: unnamed; URL [/modules/default/jnt_manageRoles/html/manageRoles.flow/view.jsp]
        at org.springframework.webflow.mvc.view.AbstractMvcView.render(AbstractMvcView.java:191)
        at org.springframework.webflow.engine.ViewState.render(ViewState.java:296)
        at org.springframework.webflow.engine.ViewState.refresh(ViewState.java:243)
        at org.springframework.webflow.engine.ViewState.resume(ViewState.java:221)
        at org.springframework.webflow.engine.Flow.resume(Flow.java:545)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:258)
        ... 173 more
Caused by: javax.servlet.ServletException: Error during servlet servicing
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:177)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handleInclude(ServletHandler.java:221)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:176)
        at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:97)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
        at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
        at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.felix.http.proxy.ProxyServlet.service(ProxyServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:229)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:264)
        at org.jahia.services.render.webflow.BundleMvcView.doRender(BundleMvcView.java:100)
        at org.springframework.webflow.mvc.view.AbstractMvcView.render(AbstractMvcView.java:187)
        ... 178 more
Caused by: org.apache.jasper.JasperException: javax.el.ELException: Problems calling function 'fn:escapeXml'
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:412)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:171)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:168)
        at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
        at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:167)
        ... 198 more
Caused by: javax.el.ELException: Problems calling function 'fn:escapeXml'
        at com.sun.el.parser.AstFunction.getValue(AstFunction.java:122)
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:206)
        at org.apache.jasper.runtime.PageContextImpl.evaluateExpression(PageContextImpl.java:1001)
        at org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp._jspx_meth_c_forEach_1(org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp:345)
        at org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp._jspx_meth_c_forEach_0(org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp:215)
        at org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp._jspService(org.apache.jsp.jnt_005fmanageRoles.html.manageRoles_flow.view_jsp:121)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:384)
        ... 205 more
Caused by: javax.el.ELException: Problems calling function 'user:displayName'
        at com.sun.el.parser.AstFunction.getValue(AstFunction.java:132)
        at com.sun.el.parser.AstFunction.getValue(AstFunction.java:118)
        ... 213 more
Caused by: java.lang.NullPointerException
        at org.jahia.data.viewhelper.principal.PrincipalViewHelper.getDisplayName(PrincipalViewHelper.java:299)
        at org.jahia.data.viewhelper.principal.PrincipalViewHelper.getDisplayName(PrincipalViewHelper.java:278)
        at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.el.parser.AstFunction.getValue(AstFunction.java:127)
        ... 214 more
